# Generated by Django 5.1.4 on 2026-02-19 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(blank=True, max_length=20)),
                ('university_type', models.CharField(choices=[('state', 'State University / SUC'), ('private', 'Private University'), ('local', 'Local College')], max_length=10)),
                ('region', models.CharField(max_length=50)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('website_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('accreditation_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ched_coe', models.BooleanField(default=False, verbose_name='CHED Center of Excellence')),
                ('ched_cod', models.BooleanField(default=False, verbose_name='CHED Center of Development')),
                ('tuition_range_min', models.PositiveIntegerField(blank=True, null=True)),
                ('tuition_range_max', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CCSProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
                ('specializations', models.JSONField(default=list)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('has_board_exam', models.BooleanField(default=False)),
                ('curriculum_url', models.URLField(blank=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university')),
            ],
            options={
                'ordering': ['abbreviation'],
            },
        ),
    ]
