# Generated by Django 5.1.4 on 2026-03-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template_name',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal'), ('executive', 'Executive'), ('sidebar-blue', 'Blueprint')], default='modern', max_length=20),
        ),
    ]
