# Generated by Django 5.1.4 on 2026-02-19 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(blank=True, max_length=30)),
                ('provider', models.CharField(choices=[('tesda', 'TESDA'), ('google', 'Google'), ('aws', 'Amazon Web Services'), ('comptia', 'CompTIA'), ('microsoft', 'Microsoft'), ('cisco', 'Cisco'), ('meta', 'Meta'), ('oracle', 'Oracle'), ('other', 'Other')], max_length=15)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=15)),
                ('description', models.TextField()),
                ('relevant_skills', models.JSONField(default=list)),
                ('career_paths', models.JSONField(default=list)),
                ('exam_url', models.URLField(blank=True)),
                ('study_guide_url', models.URLField(blank=True)),
                ('tesda_nc_level', models.CharField(blank=True, max_length=10)),
                ('is_free', models.BooleanField(default=False)),
                ('estimated_cost_php', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_study_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['provider', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('studying', 'Currently Studying'), ('passed', 'Passed / Earned'), ('expired', 'Expired')], default='interested', max_length=12)),
                ('started_studying_at', models.DateField(blank=True, null=True)),
                ('earned_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('certificate_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifications.certification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'certification')},
            },
        ),
    ]
