# Generated by Django 5.1.4 on 2026-03-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='context_type',
            field=models.CharField(choices=[('general', 'General Career Advice'), ('roadmap', 'Roadmap Discussion'), ('mentor', 'Mentor Recommendation'), ('job', 'Job Search'), ('university', 'University Selection'), ('onboarding', 'Onboarding Interview')], default='general', max_length=15),
        ),
    ]
