# Generated by Django 5.1.15 on 2026-04-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_rename_quiz_completed_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('learning', 'Learning'), ('streak', 'Streak'), ('social', 'Social'), ('certification', 'Certification'), ('completion', 'Roadmap Completion'), ('special', 'Special')], max_length=15),
        ),
        migrations.AlterField(
            model_name='xpevent',
            name='event_type',
            field=models.CharField(choices=[('node_completed', 'Completed Roadmap Node'), ('roadmap_generated', 'Generated First Roadmap'), ('daily_login', 'Daily Login'), ('badge_earned', 'Earned Badge'), ('cert_earned', 'Earned Certification'), ('profile_completed', 'Completed Profile'), ('onboarding_completed', 'Completed Onboarding')], max_length=25),
        ),
    ]
