# Generated by Django 5.1.4 on 2026-03-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Show this question only when conditions are met. Format: {"key": "interest_area", "values": ["mobile_dev"]}. Empty dict = always show.'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='key',
            field=models.CharField(blank=True, help_text='Unique slug used by other questions to reference this one in conditions.', max_length=60),
        ),
    ]
