# Generated by Django 5.1.4 on 2026-03-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_quizquestion_conditions_quizquestion_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='session',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='QuizResponse',
        ),
    ]
