# Generated by Django 5.1.4 on 2026-03-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('incoming_student', 'Incoming Student'), ('undergraduate', 'Undergraduate Student'), ('mentor', 'Mentor'), ('admin', 'Admin')], default=None, max_length=20, null=True),
        ),
    ]
