# Generated by Django 5.1.4 on 2026-03-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
