# Generated by Django 5.1.15 on 2026-04-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('incoming_student', 'Incoming Student'), ('undergraduate', 'Undergraduate Student'), ('admin', 'Admin')], default=None, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='MentorProfile',
        ),
    ]
