# Generated by Django 5.1.4 on 2026-02-19 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('career_path', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='generating', max_length=15)),
                ('ai_model_used', models.CharField(default='llama-3.3-70b-versatile', max_length=50)),
                ('flow_layout', models.JSONField(default=dict)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('estimated_weeks', models.PositiveSmallIntegerField(default=12)),
                ('is_primary', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('milestone', 'Milestone'), ('skill', 'Skill to Learn'), ('project', 'Hands-on Project'), ('assessment', 'Self-Assessment'), ('certification', 'Certification Goal')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('skill_slug', models.SlugField(blank=True, max_length=100)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('node_order', models.PositiveSmallIntegerField(default=0)),
                ('estimated_hours', models.PositiveSmallIntegerField(default=5)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='locked', max_length=15)),
                ('xp_reward', models.PositiveSmallIntegerField(default=50)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='roadmaps.roadmapnode')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='roadmaps.roadmap')),
            ],
            options={
                'ordering': ['node_order'],
            },
        ),
        migrations.CreateModel(
            name='NodeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('youtube_video', 'YouTube Video'), ('youtube_playlist', 'YouTube Playlist'), ('article', 'Article / Blog'), ('documentation', 'Official Documentation'), ('github_repo', 'GitHub Repository'), ('course', 'Online Course')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('youtube_video_id', models.CharField(blank=True, max_length=20)),
                ('youtube_channel', models.CharField(blank=True, max_length=100)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='roadmaps.roadmapnode')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NodeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmaps.roadmapnode')),
            ],
            options={
                'unique_together': {('user', 'node')},
            },
        ),
    ]
