# Generated by Django 5.1.4 on 2026-02-19 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('onboarding', 'Onboarding'), ('learning', 'Learning'), ('streak', 'Streak'), ('social', 'Social / Mentorship'), ('certification', 'Certification'), ('completion', 'Roadmap Completion'), ('special', 'Special')], max_length=15)),
                ('icon_name', models.CharField(default='star', max_length=50)),
                ('icon_color', models.CharField(default='#FFC300', max_length=7)),
                ('xp_bonus', models.PositiveSmallIntegerField(default=0)),
                ('trigger_type', models.CharField(max_length=50)),
                ('trigger_value', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('node_completed', 'Completed Roadmap Node'), ('roadmap_generated', 'Generated First Roadmap'), ('daily_login', 'Daily Login'), ('mentor_session', 'Completed Mentor Session'), ('badge_earned', 'Earned Badge'), ('cert_earned', 'Earned Certification'), ('profile_completed', 'Completed Profile'), ('quiz_completed', 'Completed Onboarding Quiz')], max_length=25)),
                ('xp_earned', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=10)),
                ('period_start', models.DateField()),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('user', 'period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
