# Generated by Django 5.1.4 on 2026-02-19 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('incoming', 'Incoming Students Only'), ('undergraduate', 'Undergraduate Students Only'), ('both', 'Both')], max_length=15)),
                ('category', models.CharField(choices=[('interest', 'Interest / Passion'), ('aptitude', 'Aptitude / Skill Level'), ('goal', 'Career Goal'), ('learning_style', 'Learning Style'), ('background', 'Background / Experience')], max_length=20)),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multi_choice', 'Multiple Choice'), ('scale', 'Likert Scale (1-5)'), ('text', 'Free Text')], max_length=15)),
                ('question_text', models.TextField()),
                ('question_text_tagalog', models.TextField(blank=True)),
                ('options', models.JSONField(default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('roadmap_generated', 'Roadmap Generated')], default='in_progress', max_length=20)),
                ('quiz_summary', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.JSONField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.quizquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='onboarding.onboardingsession')),
            ],
            options={
                'unique_together': {('session', 'question')},
            },
        ),
    ]
