# Generated by Django 5.1.4 on 2026-02-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('youtube_video', 'YouTube Video'), ('youtube_playlist', 'YouTube Playlist'), ('article', 'Article / Blog'), ('documentation', 'Official Documentation'), ('github_repo', 'GitHub Repository'), ('course', 'Online Course')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('skill_slug', models.SlugField(blank=True, max_length=100)),
                ('youtube_video_id', models.CharField(blank=True, max_length=20)),
                ('youtube_channel', models.CharField(blank=True, max_length=100)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-view_count'],
            },
        ),
    ]
